#############################################################################
# Makefile for building: OneCard
# Generated by qmake (3.1) (Qt 5.13.2)
# Project:  OneCard.pro
# Template: app
# Command: /home/peta/Felgo/Felgo/gcc_64/bin/qmake -o Makefile OneCard.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=qtquickcompiler
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../Felgo/Felgo/gcc_64/include/Felgo -I../Felgo/Felgo/gcc_64/include -I../Felgo/Felgo/gcc_64/include/QtQuick -I../Felgo/Felgo/gcc_64/include/QtWidgets -I../Felgo/Felgo/gcc_64/include/QtMultimedia -I../Felgo/Felgo/gcc_64/include/QtGui -I../Felgo/Felgo/gcc_64/include/QtWebSockets -I../Felgo/Felgo/gcc_64/include/QtQml -I../Felgo/Felgo/gcc_64/include/QtNetwork -I../Felgo/Felgo/gcc_64/include/QtSql -I../Felgo/Felgo/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../Felgo/Felgo/gcc_64/mkspecs/linux-g++
QMAKE         = /home/peta/Felgo/Felgo/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/peta/Felgo/Felgo/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/peta/Felgo/Felgo/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OneCard1.0.0
DISTDIR = /home/peta/OneCard/.tmp/OneCard1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/peta/Felgo/Felgo/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/peta/Felgo/Felgo/gcc_64/lib -lFelgo -lz /home/peta/Felgo/Felgo/gcc_64/lib/libQt5Quick.so /home/peta/Felgo/Felgo/gcc_64/lib/libQt5Widgets.so /home/peta/Felgo/Felgo/gcc_64/lib/libQt5Multimedia.so /home/peta/Felgo/Felgo/gcc_64/lib/libQt5Gui.so /home/peta/Felgo/Felgo/gcc_64/lib/libQt5WebSockets.so /home/peta/Felgo/Felgo/gcc_64/lib/libQt5Qml.so /home/peta/Felgo/Felgo/gcc_64/lib/libQt5Network.so /home/peta/Felgo/Felgo/gcc_64/lib/libQt5Sql.so /home/peta/Felgo/Felgo/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_resources_user.cpp
OBJECTS       = main.o \
		qrc_resources_user.o
DIST          = ../Felgo/Felgo/gcc_64/mkspecs/features/spec_pre.prf \
		../Felgo/Felgo/gcc_64/mkspecs/common/unix.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/linux.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/sanitize.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/gcc-base.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/g++-base.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/g++-unix.conf \
		../Felgo/Felgo/gcc_64/mkspecs/qconfig.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/features/qt_functions.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qt_config.prf \
		../Felgo/Felgo/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Felgo/Felgo/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Felgo/Felgo/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/toolchain.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/default_pre.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/resolve_config.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/default_post.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/felgo.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/resources.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qtquickcompiler.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qml_debug.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/warn_on.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qt.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/moc.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/unix/opengl.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/uic.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/unix/thread.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qmake_use.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/file_copies.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/testcase_targets.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/exceptions.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/yacc.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/lex.prf \
		OneCard.pro  main.cpp
QMAKE_TARGET  = OneCard
DESTDIR       = 
TARGET        = OneCard


first: all
####### Build rules

OneCard:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OneCard.pro ../Felgo/Felgo/gcc_64/mkspecs/linux-g++/qmake.conf ../Felgo/Felgo/gcc_64/mkspecs/features/spec_pre.prf \
		../Felgo/Felgo/gcc_64/mkspecs/common/unix.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/linux.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/sanitize.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/gcc-base.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/g++-base.conf \
		../Felgo/Felgo/gcc_64/mkspecs/common/g++-unix.conf \
		../Felgo/Felgo/gcc_64/mkspecs/qconfig.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Felgo/Felgo/gcc_64/mkspecs/features/qt_functions.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qt_config.prf \
		../Felgo/Felgo/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Felgo/Felgo/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../Felgo/Felgo/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/toolchain.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/default_pre.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/resolve_config.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/default_post.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/felgo.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/resources.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qtquickcompiler.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qml_debug.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/warn_on.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qt.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/moc.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/unix/opengl.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/uic.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/unix/thread.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/qmake_use.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/file_copies.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/testcase_targets.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/exceptions.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/yacc.prf \
		../Felgo/Felgo/gcc_64/mkspecs/features/lex.prf \
		OneCard.pro \
		../Felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc
	$(QMAKE) -o Makefile OneCard.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=qtquickcompiler
../Felgo/Felgo/gcc_64/mkspecs/features/spec_pre.prf:
../Felgo/Felgo/gcc_64/mkspecs/common/unix.conf:
../Felgo/Felgo/gcc_64/mkspecs/common/linux.conf:
../Felgo/Felgo/gcc_64/mkspecs/common/sanitize.conf:
../Felgo/Felgo/gcc_64/mkspecs/common/gcc-base.conf:
../Felgo/Felgo/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Felgo/Felgo/gcc_64/mkspecs/common/g++-base.conf:
../Felgo/Felgo/gcc_64/mkspecs/common/g++-unix.conf:
../Felgo/Felgo/gcc_64/mkspecs/qconfig.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Felgo/Felgo/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Felgo/Felgo/gcc_64/mkspecs/features/qt_functions.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/qt_config.prf:
../Felgo/Felgo/gcc_64/mkspecs/linux-g++/qmake.conf:
../Felgo/Felgo/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../Felgo/Felgo/gcc_64/mkspecs/features/exclusive_builds.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/toolchain.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/default_pre.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/resolve_config.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/default_post.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/felgo.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/resources.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/qtquickcompiler.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/qml_debug.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/warn_on.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/qt.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/moc.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/unix/opengl.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/uic.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/unix/thread.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/qmake_use.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/file_copies.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/testcase_targets.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/exceptions.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/yacc.prf:
../Felgo/Felgo/gcc_64/mkspecs/features/lex.prf:
OneCard.pro:
../Felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile OneCard.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug CONFIG+=qtquickcompiler

qmake_all: FORCE


all: Makefile OneCard

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../Felgo/Felgo/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources_user.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources_user.cpp
qrc_resources_user.cpp: ../Felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc \
		../Felgo/Felgo/gcc_64/bin/rcc \
		../Felgo/Felgo/felgo_license.key
	/home/peta/Felgo/Felgo/gcc_64/bin/rcc -name resources_user ../Felgo/Felgo/gcc_64/mkspecs/common/felgo/resources_user.qrc -o qrc_resources_user.cpp

compiler_qmlcache_make_all:
compiler_qmlcache_clean:
compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Felgo/Felgo/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h ../Felgo/Felgo/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp ../Felgo/Felgo/gcc_64/include/QtWidgets/QApplication \
		../Felgo/Felgo/gcc_64/include/QtWidgets/qapplication.h \
		../Felgo/Felgo/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qtguiglobal.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qglobal.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qconfig.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtcore-config.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsystemdetection.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qprocessordetection.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcompilerdetection.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtypeinfo.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsysinfo.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qlogging.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qflags.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qatomic.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qbasicatomic.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qgenericatomic.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qatomic_msvc.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qglobalstatic.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmutex.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qnumeric.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qversiontagging.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qtgui-config.h \
		../Felgo/Felgo/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcoreapplication.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstring.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qchar.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qbytearray.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qrefcount.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qnamespace.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qarraydata.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstringliteral.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstringalgorithms.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstringview.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstringbuilder.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qobject.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qobjectdefs.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qlist.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qalgorithms.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qiterator.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qhashfunctions.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qpair.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qvector.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qpoint.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qbytearraylist.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstringlist.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qregexp.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstringmatcher.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcoreevent.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qscopedpointer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmetatype.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qvarlengtharray.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcontainerfwd.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qobject_impl.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qeventloop.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qwindowdefs.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsize.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qcursor.h \
		../Felgo/Felgo/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../Felgo/Felgo/gcc_64/include/QtWidgets/qwidget.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmargins.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qpaintdevice.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qrect.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qpalette.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qcolor.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qrgb.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qrgba64.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qbrush.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qmatrix.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qpolygon.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qregion.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qdatastream.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qiodevice.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qline.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qtransform.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qpainterpath.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qimage.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qpixelformat.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qpixmap.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsharedpointer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qshareddata.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qhash.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qfont.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qfontmetrics.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qfontinfo.h \
		../Felgo/Felgo/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qkeysequence.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qevent.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qvariant.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmap.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qdebug.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtextstream.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qlocale.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qset.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcontiguouscache.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qurl.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qurlquery.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfile.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfiledevice.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qvector2d.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qtouchdevice.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qguiapplication.h \
		../Felgo/Felgo/gcc_64/include/QtGui/qinputmethod.h \
		../Felgo/Felgo/gcc_64/include/Felgo/FelgoApplication \
		../Felgo/Felgo/gcc_64/include/Felgo/felgoapplication.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QObject \
		../Felgo/Felgo/gcc_64/include/QtCore/QAbstractAnimation \
		../Felgo/Felgo/gcc_64/include/QtCore/qabstractanimation.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QStringList \
		../Felgo/Felgo/gcc_64/include/QtCore/QVariantMap \
		../Felgo/Felgo/gcc_64/include/QtQml/QQmlApplicationEngine \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlengine.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qjsengine.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qjsvalue.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qtqmlglobal.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qtqml-config.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmldebug.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqml.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlprivate.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlparserstatus.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmllist.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmetaobject.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlerror.h \
		../Felgo/Felgo/gcc_64/include/QtQml/QtQml \
		../Felgo/Felgo/gcc_64/include/QtQml/QtQmlDepends \
		../Felgo/Felgo/gcc_64/include/QtCore/QtCore \
		../Felgo/Felgo/gcc_64/include/QtCore/QtCoreDepends \
		../Felgo/Felgo/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qabstractitemmodel.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qabstractproxymodel.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qabstractstate.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qabstracttransition.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qanimationgroup.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qarraydataops.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qarraydatapointer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qbasictimer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qbitarray.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qbuffer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qbytearraymatcher.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcache.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcborarray.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcborvalue.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qdatetime.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcborcommon.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qregularexpression.h \
		../Felgo/Felgo/gcc_64/include/QtCore/quuid.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcbormap.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcborstream.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfloat16.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcollator.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcommandlineoption.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcommandlineparser.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qconcatenatetablesproxymodel.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qcryptographichash.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qdeadlinetimer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qelapsedtimer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qdir.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfileinfo.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qdiriterator.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qeasingcurve.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qendian.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qeventtransition.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qexception.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfactoryinterface.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfileselector.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfinalstate.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfuture.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfutureinterface.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qrunnable.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qresultstore.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qfuturewatcher.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qhistorystate.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qidentityproxymodel.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qisenum.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qitemselectionmodel.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qjsonarray.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qjsonvalue.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qjsondocument.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qjsonobject.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qlibrary.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qlibraryinfo.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qversionnumber.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qlinkedlist.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qlockfile.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qloggingcategory.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmath.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmimedata.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmimedatabase.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qmimetype.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qoperatingsystemversion.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qpauseanimation.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qplugin.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qpointer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qpluginloader.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qprocess.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qpropertyanimation.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qvariantanimation.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qqueue.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qrandom.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qreadwritelock.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qresource.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsavefile.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qscopeguard.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsemaphore.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsettings.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsharedmemory.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsignalmapper.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsignaltransition.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsocketnotifier.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstack.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstandardpaths.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstate.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstatemachine.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstorageinfo.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qstringlistmodel.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qsystemsemaphore.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtemporarydir.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtemporaryfile.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtextcodec.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qthread.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qthreadpool.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qthreadstorage.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtimeline.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtimer.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtimezone.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtranslator.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtransposeproxymodel.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtypetraits.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qwaitcondition.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qwineventnotifier.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qxmlstream.h \
		../Felgo/Felgo/gcc_64/include/QtCore/qtcoreversion.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/QtNetwork \
		../Felgo/Felgo/gcc_64/include/QtNetwork/QtNetworkDepends \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qabstractnetworkcache.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QSharedDataPointer \
		../Felgo/Felgo/gcc_64/include/QtCore/QString \
		../Felgo/Felgo/gcc_64/include/QtCore/QUrl \
		../Felgo/Felgo/gcc_64/include/QtCore/QVariant \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qauthenticator.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qdnslookup.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qdtls.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslsocket.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslerror.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslcertificate.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qssl.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QFlags \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qhostaddress.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qhostinfo.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qhstspolicy.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qhttpmultipart.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QByteArray \
		../Felgo/Felgo/gcc_64/include/QtCore/QIODevice \
		../Felgo/Felgo/gcc_64/include/QtNetwork/QNetworkRequest \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qlocalserver.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qlocalsocket.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QVector \
		../Felgo/Felgo/gcc_64/include/QtNetwork/QSslConfiguration \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QMetaType \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkconfigmanager.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkconfiguration.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkcookie.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QList \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkcookiejar.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkdatagram.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkdiskcache.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkinterface.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkproxy.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworkreply.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qnetworksession.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qocspresponse.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qpassworddigestor.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QCryptographicHash \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsctpserver.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qtcpserver.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsctpsocket.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslcertificateextension.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslcipher.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qssldiffiehellmanparameters.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslellipticcurve.h \
		../Felgo/Felgo/gcc_64/include/QtCore/QHash \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qsslkey.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qudpsocket.h \
		../Felgo/Felgo/gcc_64/include/QtNetwork/qtnetworkversion.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qjsvalueiterator.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlabstracturlinterceptor.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlcomponent.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlcontext.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlexpression.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlscriptstring.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlextensioninterface.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlextensionplugin.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlfile.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlfileselector.h \
		../Felgo/Felgo/gcc_64/include/QtQml/QQmlEngine \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlincubator.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlinfo.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlnetworkaccessmanagerfactory.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlproperty.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qqmlpropertymap.h \
		../Felgo/Felgo/gcc_64/include/QtQml/qtqmlversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_resources_user.o: qrc_resources_user.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources_user.o qrc_resources_user.cpp

####### Install

install_itemqmlFolder: first FORCE
	@test -d $(INSTALL_ROOT)/home/peta/OneCard || mkdir -p $(INSTALL_ROOT)/home/peta/OneCard
	-$(QINSTALL) /home/peta/OneCard/qml $(INSTALL_ROOT)/home/peta/OneCard/qml

uninstall_itemqmlFolder: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/peta/OneCard/qml
	-$(DEL_DIR) $(INSTALL_ROOT)/home/peta/OneCard/ 


install_itemassetsFolder: first FORCE
	@test -d $(INSTALL_ROOT)/home/peta/OneCard || mkdir -p $(INSTALL_ROOT)/home/peta/OneCard
	-$(QINSTALL) /home/peta/OneCard/assets $(INSTALL_ROOT)/home/peta/OneCard/assets

uninstall_itemassetsFolder: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/peta/OneCard/assets
	-$(DEL_DIR) $(INSTALL_ROOT)/home/peta/OneCard/ 


install: install_itemqmlFolder install_itemassetsFolder  FORCE

uninstall: uninstall_itemqmlFolder uninstall_itemassetsFolder  FORCE

FORCE:

