#############################################################################
# Makefile for building: Karma.app/Contents/MacOS/Karma
# Generated by qmake (3.1) (Qt 5.13.2)
# Project:  Karma.pro
# Template: app
# Command: /Users/hannaschwarz/Felgo/Felgo/ios/bin/qmake -o Karma.xcodeproj/project.pbxproj Karma.pro -spec macx-xcode CONFIG+=release CONFIG+=iphoneos CONFIG+=device CONFIG+=qtquickcompiler QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=J3NF8C2WLY
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /Users/hannaschwarz/Felgo/Felgo/ios/bin/moc
UIC       = /Users/hannaschwarz/Felgo/Felgo/ios/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2 -DPRODUCT_LICENSE_KEY=\"33A5BD15029EDFE6AF6AF969C029F7786A1C304D56C89FC73C5E36188F5B1AE06FF53FB58F5C61CE57691DD9F4B8F17F8CC9B62D5E3A8609F9834FD1299F83177A99EDC4255310E92F817EA57D9D4EFC54D98F2B6EBA794AF00C5D6A74C09258346A843B4F37F5D488365FF0FA0B07F1D84AEDD05AC8203AAB5DB4DCE8BA0B8475774E1EA91B31E9D93D4222145B45D7CB3D4A86D36BEEF4113797F87C3401AA0F917B0680AC19682579201C77303D7BEADB2245A4E45483D807764516BC868E86B66CF619D4D58D7D7F12A927A1AA2EE06284AF90D0E57492BF003C6A72DFD4E0112C97CF215DEBAACA77F0BFF3CA44B7B043B137D7177CB6257AB43E46E7DFBAF9E0CDEF8315DAF8664FB485D8B2425F4B92CBED621599495EA19E28C372F1FEE0BD20B2AF136C02577D07DE80321482F5E6953E0298788E40D6F1F252F1EBDC9F18E619E825BA764E5FBAF59F9426\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_WEBSOCKETS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
INCPATH       = -I. -I../Felgo/Felgo/ios/mkspecs/common/uikit -I../Felgo/Felgo/ios/include/Felgo -I../Felgo/Felgo/ios/include -I../Felgo/Felgo/ios/include/QtQuick -I../Felgo/Felgo/ios/include/QtWidgets -I../Felgo/Felgo/ios/include/QtMultimedia -I../Felgo/Felgo/ios/include/QtGui -I../Felgo/Felgo/ios/include/QtWebSockets -I../Felgo/Felgo/ios/include/QtQml -I../Felgo/Felgo/ios/include/QtNetwork -I../Felgo/Felgo/ios/include/QtSql -I../Felgo/Felgo/ios/include/QtCore -I. -I../Felgo/Felgo/ios/mkspecs/macx-ios-clang
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_resources_qmlcache.cpp qrc_resources_user.cpp qml_interface_SwitchNameWindow_qml.cpp qml_scenes_InstructionScene_qml.cpp qml_common_SwipeArea_qml.cpp\
	 qml_scenes_GameNetworkScene_qml.cpp qml_scenes_LoadingScene_qml.cpp qml_common_GConsole_qml.cpp\
	 qml_interface_LikeWindow_qml.cpp qml_common_SceneBase_qml.cpp qml_game_Deck_qml.cpp\
	 qml_scenes_CardScene_qml.cpp qml_interface_GameOverWindow_qml.cpp qml_ShitheadMain_qml.cpp\
	 qml_game_Depot_qml.cpp qml_game_Removed_qml.cpp qml_interface_LeaveGameWindow_qml.cpp\
	 qml_ShitheadMainItem_qml.cpp qml_interface_PlayerTag_qml.cpp qml_interface_PlayerInfo_qml.cpp\
	 qml_scenes_MultiplayerScene_qml.cpp qml_common_Constants_qml.cpp qml_scenes_MenuScene_qml.cpp\
	 qml_common_ButtonBase_qml.cpp qml_interface_Chat_qml.cpp qml_game_GameLogic_qml.cpp\
	 qml_common_MenuButton_qml.cpp qml_game_PlayerHand_qml.cpp qml_scenes_GameScene_qml.cpp\
	 qml_game_Card_qml.cpp qml_common_ButtonBase_qml.cpp qml_common_SceneBase_qml.cpp\
	 qml_common_SwipeArea_qml.cpp qml_common_MenuButton_qml.cpp qml_common_GConsole_qml.cpp\
	 qml_common_Constants_qml.cpp qml_scenes_MenuScene_qml.cpp qml_scenes_GameScene_qml.cpp\
	 qml_scenes_CardScene_qml.cpp qml_scenes_InstructionScene_qml.cpp qml_scenes_MultiplayerScene_qml.cpp\
	 qml_scenes_LoadingScene_qml.cpp qml_scenes_GameNetworkScene_qml.cpp qml_game_PlayerHand_qml.cpp\
	 qml_game_Card_qml.cpp qml_game_Removed_qml.cpp qml_game_Depot_qml.cpp\
	 qml_game_GameLogic_qml.cpp qml_game_Deck_qml.cpp qml_interface_PlayerTag_qml.cpp\
	 qml_interface_LeaveGameWindow_qml.cpp qml_interface_SwitchNameWindow_qml.cpp qml_interface_PlayerInfo_qml.cpp\
	 qml_interface_GameOverWindow_qml.cpp qml_interface_LikeWindow_qml.cpp qml_interface_Chat_qml.cpp qmlcache_loader.cpp
compiler_rcc_make_all: qrc_resources_qmlcache.cpp qrc_resources_user.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources_qmlcache.cpp qrc_resources_user.cpp
qrc_resources_qmlcache.cpp: resources_qmlcache.qrc \
		../Felgo/Felgo/ios/bin/rcc \
		qml/interface/SwitchNameWindow.qml \
		qml/scenes/InstructionScene.qml \
		qml/common/SwipeArea.qml \
		qml/scenes/GameNetworkScene.qml \
		qml/scenes/LoadingScene.qml \
		qml/common/GConsole.qml \
		qml/config.json \
		qml/interface/LikeWindow.qml \
		qml/common/SceneBase.qml \
		qml/game/Deck.qml \
		qml/scenes/CardScene.qml \
		qml/interface/GameOverWindow.qml \
		qml/ShitheadMain.qml \
		qml/game/Depot.qml \
		qml/game/Removed.qml \
		qml/interface/LeaveGameWindow.qml \
		qml/ShitheadMainItem.qml \
		qml/common/qmldir \
		qml/interface/PlayerTag.qml \
		qml/interface/PlayerInfo.qml \
		qml/scenes/MultiplayerScene.qml \
		qml/common/Constants.qml \
		qml/scenes/MenuScene.qml \
		qml/common/ButtonBase.qml \
		qml/interface/Chat.qml \
		qml/game/GameLogic.qml \
		qml/common/MenuButton.qml \
		qml/game/PlayerHand.qml \
		qml/scenes/GameScene.qml \
		qml/game/Card.qml \
		qml/common/ButtonBase.qml \
		qml/common/SceneBase.qml \
		qml/common/SwipeArea.qml \
		qml/common/MenuButton.qml \
		qml/common/GConsole.qml \
		qml/common/Constants.qml \
		qml/common/qmldir \
		qml/scenes/MenuScene.qml \
		qml/scenes/GameScene.qml \
		qml/scenes/CardScene.qml \
		qml/scenes/InstructionScene.qml \
		qml/scenes/MultiplayerScene.qml \
		qml/scenes/LoadingScene.qml \
		qml/scenes/GameNetworkScene.qml \
		qml/game/PlayerHand.qml \
		qml/game/Card.qml \
		qml/game/Removed.qml \
		qml/game/Depot.qml \
		qml/game/GameLogic.qml \
		qml/game/Deck.qml \
		qml/interface/PlayerTag.qml \
		qml/interface/LeaveGameWindow.qml \
		qml/interface/SwitchNameWindow.qml \
		qml/interface/PlayerInfo.qml \
		qml/interface/GameOverWindow.qml \
		qml/interface/LikeWindow.qml \
		qml/interface/Chat.qml
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/rcc -name resources_qmlcache resources_qmlcache.qrc -o qrc_resources_qmlcache.cpp

qrc_resources_user.cpp: ../Felgo/Felgo/ios/mkspecs/common/felgo/resources_user.qrc \
		../Felgo/Felgo/ios/bin/rcc \
		../Felgo/Felgo/felgo_license.key
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/rcc -name resources_user ../Felgo/Felgo/ios/mkspecs/common/felgo/resources_user.qrc -o qrc_resources_user.cpp

compiler_qmlcache_make_all: qml_interface_SwitchNameWindow_qml.cpp qml_scenes_InstructionScene_qml.cpp qml_common_SwipeArea_qml.cpp qml_scenes_GameNetworkScene_qml.cpp qml_scenes_LoadingScene_qml.cpp qml_common_GConsole_qml.cpp qml_interface_LikeWindow_qml.cpp qml_common_SceneBase_qml.cpp qml_game_Deck_qml.cpp qml_scenes_CardScene_qml.cpp qml_interface_GameOverWindow_qml.cpp qml_ShitheadMain_qml.cpp qml_game_Depot_qml.cpp qml_game_Removed_qml.cpp qml_interface_LeaveGameWindow_qml.cpp qml_ShitheadMainItem_qml.cpp qml_interface_PlayerTag_qml.cpp qml_interface_PlayerInfo_qml.cpp qml_scenes_MultiplayerScene_qml.cpp qml_common_Constants_qml.cpp qml_scenes_MenuScene_qml.cpp qml_common_ButtonBase_qml.cpp qml_interface_Chat_qml.cpp qml_game_GameLogic_qml.cpp qml_common_MenuButton_qml.cpp qml_game_PlayerHand_qml.cpp qml_scenes_GameScene_qml.cpp qml_game_Card_qml.cpp qml_common_ButtonBase_qml.cpp qml_common_SceneBase_qml.cpp qml_common_SwipeArea_qml.cpp qml_common_MenuButton_qml.cpp qml_common_GConsole_qml.cpp qml_common_Constants_qml.cpp qml_scenes_MenuScene_qml.cpp qml_scenes_GameScene_qml.cpp qml_scenes_CardScene_qml.cpp qml_scenes_InstructionScene_qml.cpp qml_scenes_MultiplayerScene_qml.cpp qml_scenes_LoadingScene_qml.cpp qml_scenes_GameNetworkScene_qml.cpp qml_game_PlayerHand_qml.cpp qml_game_Card_qml.cpp qml_game_Removed_qml.cpp qml_game_Depot_qml.cpp qml_game_GameLogic_qml.cpp qml_game_Deck_qml.cpp qml_interface_PlayerTag_qml.cpp qml_interface_LeaveGameWindow_qml.cpp qml_interface_SwitchNameWindow_qml.cpp qml_interface_PlayerInfo_qml.cpp qml_interface_GameOverWindow_qml.cpp qml_interface_LikeWindow_qml.cpp qml_interface_Chat_qml.cpp
compiler_qmlcache_clean:
	-$(DEL_FILE) qml_interface_SwitchNameWindow_qml.cpp qml_scenes_InstructionScene_qml.cpp qml_common_SwipeArea_qml.cpp qml_scenes_GameNetworkScene_qml.cpp qml_scenes_LoadingScene_qml.cpp qml_common_GConsole_qml.cpp qml_interface_LikeWindow_qml.cpp qml_common_SceneBase_qml.cpp qml_game_Deck_qml.cpp qml_scenes_CardScene_qml.cpp qml_interface_GameOverWindow_qml.cpp qml_ShitheadMain_qml.cpp qml_game_Depot_qml.cpp qml_game_Removed_qml.cpp qml_interface_LeaveGameWindow_qml.cpp qml_ShitheadMainItem_qml.cpp qml_interface_PlayerTag_qml.cpp qml_interface_PlayerInfo_qml.cpp qml_scenes_MultiplayerScene_qml.cpp qml_common_Constants_qml.cpp qml_scenes_MenuScene_qml.cpp qml_common_ButtonBase_qml.cpp qml_interface_Chat_qml.cpp qml_game_GameLogic_qml.cpp qml_common_MenuButton_qml.cpp qml_game_PlayerHand_qml.cpp qml_scenes_GameScene_qml.cpp qml_game_Card_qml.cpp qml_common_ButtonBase_qml.cpp qml_common_SceneBase_qml.cpp qml_common_SwipeArea_qml.cpp qml_common_MenuButton_qml.cpp qml_common_GConsole_qml.cpp qml_common_Constants_qml.cpp qml_scenes_MenuScene_qml.cpp qml_scenes_GameScene_qml.cpp qml_scenes_CardScene_qml.cpp qml_scenes_InstructionScene_qml.cpp qml_scenes_MultiplayerScene_qml.cpp qml_scenes_LoadingScene_qml.cpp qml_scenes_GameNetworkScene_qml.cpp qml_game_PlayerHand_qml.cpp qml_game_Card_qml.cpp qml_game_Removed_qml.cpp qml_game_Depot_qml.cpp qml_game_GameLogic_qml.cpp qml_game_Deck_qml.cpp qml_interface_PlayerTag_qml.cpp qml_interface_LeaveGameWindow_qml.cpp qml_interface_SwitchNameWindow_qml.cpp qml_interface_PlayerInfo_qml.cpp qml_interface_GameOverWindow_qml.cpp qml_interface_LikeWindow_qml.cpp qml_interface_Chat_qml.cpp
qml_interface_SwitchNameWindow_qml.cpp: qml/interface/SwitchNameWindow.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_SwitchNameWindow_qml.cpp qml/interface/SwitchNameWindow.qml

qml_scenes_InstructionScene_qml.cpp: qml/scenes/InstructionScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_InstructionScene_qml.cpp qml/scenes/InstructionScene.qml

qml_common_SwipeArea_qml.cpp: qml/common/SwipeArea.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_SwipeArea_qml.cpp qml/common/SwipeArea.qml

qml_scenes_GameNetworkScene_qml.cpp: qml/scenes/GameNetworkScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_GameNetworkScene_qml.cpp qml/scenes/GameNetworkScene.qml

qml_scenes_LoadingScene_qml.cpp: qml/scenes/LoadingScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_LoadingScene_qml.cpp qml/scenes/LoadingScene.qml

qml_common_GConsole_qml.cpp: qml/common/GConsole.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_GConsole_qml.cpp qml/common/GConsole.qml

qml_interface_LikeWindow_qml.cpp: qml/interface/LikeWindow.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_LikeWindow_qml.cpp qml/interface/LikeWindow.qml

qml_common_SceneBase_qml.cpp: qml/common/SceneBase.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_SceneBase_qml.cpp qml/common/SceneBase.qml

qml_game_Deck_qml.cpp: qml/game/Deck.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_Deck_qml.cpp qml/game/Deck.qml

qml_scenes_CardScene_qml.cpp: qml/scenes/CardScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_CardScene_qml.cpp qml/scenes/CardScene.qml

qml_interface_GameOverWindow_qml.cpp: qml/interface/GameOverWindow.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_GameOverWindow_qml.cpp qml/interface/GameOverWindow.qml

qml_ShitheadMain_qml.cpp: qml/ShitheadMain.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_ShitheadMain_qml.cpp qml/ShitheadMain.qml

qml_game_Depot_qml.cpp: qml/game/Depot.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_Depot_qml.cpp qml/game/Depot.qml

qml_game_Removed_qml.cpp: qml/game/Removed.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_Removed_qml.cpp qml/game/Removed.qml

qml_interface_LeaveGameWindow_qml.cpp: qml/interface/LeaveGameWindow.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_LeaveGameWindow_qml.cpp qml/interface/LeaveGameWindow.qml

qml_ShitheadMainItem_qml.cpp: qml/ShitheadMainItem.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_ShitheadMainItem_qml.cpp qml/ShitheadMainItem.qml

qml_interface_PlayerTag_qml.cpp: qml/interface/PlayerTag.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_PlayerTag_qml.cpp qml/interface/PlayerTag.qml

qml_interface_PlayerInfo_qml.cpp: qml/interface/PlayerInfo.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_PlayerInfo_qml.cpp qml/interface/PlayerInfo.qml

qml_scenes_MultiplayerScene_qml.cpp: qml/scenes/MultiplayerScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_MultiplayerScene_qml.cpp qml/scenes/MultiplayerScene.qml

qml_common_Constants_qml.cpp: qml/common/Constants.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_Constants_qml.cpp qml/common/Constants.qml

qml_scenes_MenuScene_qml.cpp: qml/scenes/MenuScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_MenuScene_qml.cpp qml/scenes/MenuScene.qml

qml_common_ButtonBase_qml.cpp: qml/common/ButtonBase.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_ButtonBase_qml.cpp qml/common/ButtonBase.qml

qml_interface_Chat_qml.cpp: qml/interface/Chat.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_Chat_qml.cpp qml/interface/Chat.qml

qml_game_GameLogic_qml.cpp: qml/game/GameLogic.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_GameLogic_qml.cpp qml/game/GameLogic.qml

qml_common_MenuButton_qml.cpp: qml/common/MenuButton.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_MenuButton_qml.cpp qml/common/MenuButton.qml

qml_game_PlayerHand_qml.cpp: qml/game/PlayerHand.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_PlayerHand_qml.cpp qml/game/PlayerHand.qml

qml_scenes_GameScene_qml.cpp: qml/scenes/GameScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_GameScene_qml.cpp qml/scenes/GameScene.qml

qml_game_Card_qml.cpp: qml/game/Card.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_Card_qml.cpp qml/game/Card.qml

qml_common_ButtonBase_qml.cpp: qml/common/ButtonBase.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_ButtonBase_qml.cpp qml/common/ButtonBase.qml

qml_common_SceneBase_qml.cpp: qml/common/SceneBase.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_SceneBase_qml.cpp qml/common/SceneBase.qml

qml_common_SwipeArea_qml.cpp: qml/common/SwipeArea.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_SwipeArea_qml.cpp qml/common/SwipeArea.qml

qml_common_MenuButton_qml.cpp: qml/common/MenuButton.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_MenuButton_qml.cpp qml/common/MenuButton.qml

qml_common_GConsole_qml.cpp: qml/common/GConsole.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_GConsole_qml.cpp qml/common/GConsole.qml

qml_common_Constants_qml.cpp: qml/common/Constants.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_common_Constants_qml.cpp qml/common/Constants.qml

qml_scenes_MenuScene_qml.cpp: qml/scenes/MenuScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_MenuScene_qml.cpp qml/scenes/MenuScene.qml

qml_scenes_GameScene_qml.cpp: qml/scenes/GameScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_GameScene_qml.cpp qml/scenes/GameScene.qml

qml_scenes_CardScene_qml.cpp: qml/scenes/CardScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_CardScene_qml.cpp qml/scenes/CardScene.qml

qml_scenes_InstructionScene_qml.cpp: qml/scenes/InstructionScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_InstructionScene_qml.cpp qml/scenes/InstructionScene.qml

qml_scenes_MultiplayerScene_qml.cpp: qml/scenes/MultiplayerScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_MultiplayerScene_qml.cpp qml/scenes/MultiplayerScene.qml

qml_scenes_LoadingScene_qml.cpp: qml/scenes/LoadingScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_LoadingScene_qml.cpp qml/scenes/LoadingScene.qml

qml_scenes_GameNetworkScene_qml.cpp: qml/scenes/GameNetworkScene.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_scenes_GameNetworkScene_qml.cpp qml/scenes/GameNetworkScene.qml

qml_game_PlayerHand_qml.cpp: qml/game/PlayerHand.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_PlayerHand_qml.cpp qml/game/PlayerHand.qml

qml_game_Card_qml.cpp: qml/game/Card.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_Card_qml.cpp qml/game/Card.qml

qml_game_Removed_qml.cpp: qml/game/Removed.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_Removed_qml.cpp qml/game/Removed.qml

qml_game_Depot_qml.cpp: qml/game/Depot.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_Depot_qml.cpp qml/game/Depot.qml

qml_game_GameLogic_qml.cpp: qml/game/GameLogic.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_GameLogic_qml.cpp qml/game/GameLogic.qml

qml_game_Deck_qml.cpp: qml/game/Deck.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_game_Deck_qml.cpp qml/game/Deck.qml

qml_interface_PlayerTag_qml.cpp: qml/interface/PlayerTag.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_PlayerTag_qml.cpp qml/interface/PlayerTag.qml

qml_interface_LeaveGameWindow_qml.cpp: qml/interface/LeaveGameWindow.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_LeaveGameWindow_qml.cpp qml/interface/LeaveGameWindow.qml

qml_interface_SwitchNameWindow_qml.cpp: qml/interface/SwitchNameWindow.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_SwitchNameWindow_qml.cpp qml/interface/SwitchNameWindow.qml

qml_interface_PlayerInfo_qml.cpp: qml/interface/PlayerInfo.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_PlayerInfo_qml.cpp qml/interface/PlayerInfo.qml

qml_interface_GameOverWindow_qml.cpp: qml/interface/GameOverWindow.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_GameOverWindow_qml.cpp qml/interface/GameOverWindow.qml

qml_interface_LikeWindow_qml.cpp: qml/interface/LikeWindow.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_LikeWindow_qml.cpp qml/interface/LikeWindow.qml

qml_interface_Chat_qml.cpp: qml/interface/Chat.qml \
		../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource=/Users/hannaschwarz/Karma/resources.qrc -o qml_interface_Chat_qml.cpp qml/interface/Chat.qml

compiler_qmlcache_loader_make_all: qmlcache_loader.cpp
compiler_qmlcache_loader_clean:
	-$(DEL_FILE) qmlcache_loader.cpp
qmlcache_loader.cpp: resources.qrc ../Felgo/Felgo/ios/bin/qmlcachegen
	/Users/hannaschwarz/Felgo/Felgo/ios/bin/qmlcachegen --resource-file-mapping=/Users/hannaschwarz/Karma/resources.qrc=/Users/hannaschwarz/Karma/resources_qmlcache.qrc -o qmlcache_loader.cpp resources.qrc

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_qmlcache_clean compiler_qmlcache_loader_clean 

